export {
	ABOUT_PAGE_QUERY,
	GET_FAQS_PAGES,
	GET_THEME_PAGE,
	HOME_PAGE_QUERY,
	IMAGE_WITH_ALT_FRAGMENT_IMAGE_WITH_ALT,
	MAIN_NAVIGATION_QUERY,
	TESTIMONIALS_PAGE_QUERY,
} from './graphql';
export { sanityClient } from './sanity-client';
