// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:theme/collections/:collection": {
    params: {
      "theme": string;
      "collection": string;
    };
  };
  "/:theme/products/:handle": {
    params: {
      "theme": string;
      "handle": string;
    };
  };
  "/terms-and-conditions": {
    params: {};
  };
  "/blogs/tips/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/newsletter": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/refund-policy": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/testimonials": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/:theme": {
    params: {
      "theme": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/faq": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:theme/collections/:collection" | "/:theme/products/:handle" | "/terms-and-conditions" | "/blogs/tips/:slug" | "/api/newsletter" | "/privacy-policy" | "/sitemap.xml" | "/refund-policy" | "/robots.txt" | "/testimonials" | "/api/contact" | "/blog" | "/blog/:slug" | "/:theme" | "/contact" | "/about" | "/cart" | "/faq";
  };
  "routes/$theme.collections.$collection.tsx": {
    id: "routes/$theme.collections.$collection";
    page: "/:theme/collections/:collection";
  };
  "routes/$theme.products.$handle.tsx": {
    id: "routes/$theme.products.$handle";
    page: "/:theme/products/:handle";
  };
  "routes/terms-and-conditions.tsx": {
    id: "routes/terms-and-conditions";
    page: "/terms-and-conditions";
  };
  "routes/blogs.tips.$slug.tsx": {
    id: "routes/blogs.tips.$slug";
    page: "/blogs/tips/:slug";
  };
  "routes/api.newsletter.tsx": {
    id: "routes/api.newsletter";
    page: "/api/newsletter";
  };
  "routes/privacy-policy.tsx": {
    id: "routes/privacy-policy";
    page: "/privacy-policy";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/refund-policy.tsx": {
    id: "routes/refund-policy";
    page: "/refund-policy";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/testimonials.tsx": {
    id: "routes/testimonials";
    page: "/testimonials";
  };
  "routes/api.contact.tsx": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/$theme_.tsx": {
    id: "routes/$theme_";
    page: "/:theme";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
};